file=open("hello.txt",'rb')
print(file)
content1=file.read()
print(content1)
print()
file.close()
new_file=open("new_file.txt",'w')
new_file.write("hello im new file")
new_file.close()
latest_file=open("new_file.txt",'a')
latest_file.write("   hello ")
latest_file.close()
printing=open("new_file.txt")
content=printing.read()
print(content)
last_file=open("new_file.txt",'w')
last_file.write("ok")
last_file.close()
lastest=open("new_file.txt")
lastt=lastest.read()
print(lastt)

with open("new_file.txt",'a') as s:
    s.write("")
